package sort;

import java.util.HashMap;
import java.util.Map;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class SelectionSort {
	
	private Long troca;
	private Long compara;

	public SelectionSort() {
		this.troca = 0L;
		this.compara = 0L;
	}
	
	public void selectionSort(int[] array) {
		for (Integer fixo = 0; fixo < array.length - 1; fixo++) {
			Integer menor = fixo;
			for (Integer i = menor + 1; i < array.length; i++) {
				compara++; 
				if (array[i] < array[menor]) {
					menor = i;
				}
			}
			if (menor != fixo) {
				troca(array, fixo, menor);
				troca++;
			}
		}
	}

	private void troca(int[] array, Integer fixo, Integer menor) {
		int t = array[fixo];
		array[fixo] = array[menor];
		array[menor] = t;
	}

	public Map<String, Long> getRetornaDados() {
		Map<String, Long> retornoDados = new HashMap<String, Long>();
		retornoDados.put(SortKeys.KEY_TROCA, troca);
		retornoDados.put(SortKeys.KEY_COMPARA, compara);
		return retornoDados;
	}
	
}
