package sort;

import java.util.HashMap;
import java.util.Map;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class SelectionSort {
	
	private Long troca;
	private Long compara;

	public SelectionSort() {
		this.troca = 0L;
		this.compara = 0L;
	}
	
	public void selectionSort(int[] vetor) {
		for (Integer fixo = 0; fixo < vetor.length - 1; fixo++) {
			Integer menor = fixo;
			for (Integer i = menor + 1; i < vetor.length; i++) {
				compara++;
				if (vetor[i] < vetor[menor]) {
					menor = i;
				}
			}
			if (menor != fixo) {
				troca(vetor, fixo, menor);
			}
		}
	}

	private void troca(int[] array, Integer fixo, Integer menor) {
		int temp = array[fixo];
		array[fixo] = array[menor];
		array[menor] = temp;
		troca++;
	}

	public Map<String, Long> getRetornaDados() {
		Map<String, Long> retornoDados = new HashMap<String, Long>();
		retornoDados.put(SortKeys.KEY_TROCA, troca);
		retornoDados.put(SortKeys.KEY_COMPARA, compara);
		return retornoDados;
	}
	
}
