package sort;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class SelectionSortTest {
	
	@Test
	public void testSomeLibraryMethod() {
		int quantidade = 10000;
		int[] vetor = new int[quantidade];
		for (int i = 0; i < vetor.length; i++) {
			vetor[i] = (int) (Math.random() * quantidade);
		}
		long tempoInicial = System.currentTimeMillis();
		SelectionSort selectionSort = new SelectionSort();
		selectionSort.selectionSort(vetor);
		long tempoFinal = System.currentTimeMillis();
		System.out.println("Executado em = " + (tempoFinal - tempoInicial) + " ms");
	}
	
}
